live_config_reload = true

import = [
    #"~/.config/alacritty/themes/themes/ayu_dark.toml"
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 10.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Semibold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Semibold"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
